Ejercicios/Ejercicios/Models/Accesos.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Ejercicios.Models
{
    public class Accesos
    {
       public string[] Users = new string[3] { "Lopez", "Pedro", "WIlliam" };
       public int[] Dui = new int[3] {12345, 123456, 1234567};
    }
}

Ejercicios/Ejercicios/Controllers/EjerciciosController.cs
using Ejercicios.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ejercicios.Controllers
{
    public class EjerciciosController : Controller
    {
        // GET: Ejercicios
        public ActionResult Index()
        {
            return View();
        }

        Accesos users = new Accesos();
        [HttpPost]
        public ActionResult Login(string User, int dui)
        {
            

            for (int i = 0; i < users.Users.Length; i++)
                if (User.Equals(users.Users[i]) && dui.Equals(users.Dui[i]))
                {
                    return Redirect("/Ejercicios/obtDatos");
                }
                
                ViewBag.Error = "Usuario o password incorrecta";
               
                return RedirectToAction("Index");
        }

        

       

        public ActionResult obtDatos(string nombre, float valorhr=0, float hrstrab=0, float antiguedad=0 )
        {
            ViewBag.nombre = nombre;
            ViewBag.valorhoras = valorhr;
            ViewBag.horastrab = hrstrab;
            ViewBag.antiguedad = antiguedad;
            ViewBag.cobro = (valorhr * hrstrab + antiguedad + 30);
            ViewBag.descuento = ((valorhr * hrstrab + antiguedad * 30) * 0.13);
            ViewBag.condescuento = ((valorhr * hrstrab + antiguedad * 30) - (valorhr * hrstrab + antiguedad * 30) * 0.13);
            return View();
        }
    }
}

Ejercicios/Ejercicios/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ejercicios.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Ejercicios/Ejercicios/Views/Ejercicios/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    

</head>
<body>
    <div> 
        <h2<Login</h2>
        @using (Html.BeginForm("Login", "Ejercicios", FormMethod.Post))
        {
            <label for="User">Usuario</label>
            <input name="User" id="user" type="text" placeholder="Usuario"  />
            <br/>
            <label for="dui">DUI</label>
            <input name="dui" id="dui" type="number" placeholder="DUI"  />
            <br />
            <label style="color = black" value=@ViewBag.Error></label>
            <br />
            <input type="submit" value="Ingresar" />
        }
    </div>
</body>
</html>

Ejercicios/Ejercicios/Views/Ejercicios/obtDatos.cshtml
@{
    ViewBag.Title = "abtDatos";
}

<h2>Ingrese sus datos</h2>

@using (Html.BeginForm("obtDatos", "Ejercicios"))
{
    <label for="nombre">Usuario</label>
            <input name="nombre" id="nombew" type="text"  value=@ViewBag.nombre />
            <br />
            <label for="valorhri">valor de hora</label>
            <input name="valorhr" id="valorhr" type="number"  value=@ViewBag.valorhoras />
            <br />
            <label for="hrstrab">horas trabajadas</label>
            <input name="hrstrab" id="hrstrab" type="number" value=@ViewBag.horastrab />
            <br /><label for="antiguedad">antiguedad</label>
            <input name="antiguedad" id="antiguedad" type="number"  value=@ViewBag.antiguedad />
            <br /><label for="totalcobrar">total a cobrar</label>
            <input name="totalcobrar" id="totalcobrar" type="number"  readonly value=@ViewBag.cobro  />
            <br /><label for="descuento">total del descuento</label>
            <input name="descuento" id="descuento" type="number"  readonly value=@ViewBag.descuento />
            <br />
            <br /><label for="condescuento">total con descuento</label>
            <input name="condescuento" id="condescuento" type="number"  readonly value=@ViewBag.condescuento />
            <br />
            <input type="submit" value="Ingresar" />
}

Ejercicios/Ejercicios/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Ejercicios/Ejercicios/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Ejercicios/Ejercicios/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Ejercicios/Ejercicios/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
        
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                    <li>@Html.ActionLink("Datos", "obtDatos", "Ejercicios")</li>
                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>